produto:
    pattern:  /
    defaults: { _controller: "CategoriaBundle:Produto:index" }

produto_show:
    pattern:  /{id}/show
    defaults: { _controller: "CategoriaBundle:Produto:show" }

produto_new:
    pattern:  /new
    defaults: { _controller: "CategoriaBundle:Produto:new" }

produto_create:
    pattern:  /create
    defaults: { _controller: "CategoriaBundle:Produto:create" }
    requirements: { _method: post }

produto_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CategoriaBundle:Produto:edit" }

produto_update:
    pattern:  /{id}/update
    defaults: { _controller: "CategoriaBundle:Produto:update" }
    requirements: { _method: post }

produto_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CategoriaBundle:Produto:delete" }
    requirements: { _method: post }
