parameters:
#    categoria.example.class: SON\CategoriaBundle\Example

services:
#    categoria.example:
#        class: %categoria.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
