categoria:
    resource: "@CategoriaBundle/Resources/config/routing.yml"
    prefix:   /

catalogo:
    resource: "@CatalogoBundle/Resources/config/routing.yml"
    prefix:   /

UserBundle:
    resource: "@UserBundle/Controller"
    prefix:   /
    type:     annotation

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
