catalogo_homepage:
    pattern:  /hello/{name}/{quantidade}
    defaults: { _controller: CatalogoBundle:Default:index }

CatalogoBundle_catalogo:
   resource: "@CatalogoBundle/Resources/config/routing/catalogo.yml"
   prefix:   /

CatalogoBundle_catalogo_annotation:
  resource: "@CatalogoBundle/Controller"
  prefix:   /
  type: annotation