parameters:
#    catalogo.example.class: SON\CatalogoBundle\Example

services:
#    catalogo.example:
#        class: %catalogo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
